version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: ls -alh
  test:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker
      - run: docker images
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
